### ISSUE TITLE
Fix compile

### ISSUE THREAD

**Issue by cdalmasso** [dotnet/docs.fr-fr#105]
To compile when using List&lt;Repository&gt; it is necessary to add 
using System.Collections.Generic;
using WebAPIClient;
in order to compile

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Crée un client REST à l’aide de .NET Core](https://docs.microsoft.com/fr-fr/dotnet/csharp/tutorials/console-webapiclient#feedback)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @cdalmasso
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @cdalmasso, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/18539. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
