### ISSUE TITLE
How can we start translating a file ?

### ISSUE THREAD

**Issue by Ssiws** [dotnet/docs.fr-fr#8]
How can I start translating, for example this file: https://docs.microsoft.com/fr-fr/dotnet/articles/csharp/getting-started/ into french ?

When I click on "Edit", I'm redirected here: https://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/index.md (English version of the file)

**Comment by mairaw** [comment]
That happens when the article in a certain locale hasn't been published or doesn't exist. Then, what you see is the the English version of the topic. 

These topics are being localized and you can find the French version here already:
https://github.com/dotnet/docs.fr-fr/blob/master/docs/csharp/getting-started/index.md

It should get published soon. /cc @nokura

**Comment by Ssiws** [comment]
Ok, thank you for your answer
